# Generated by Django 2.0.2 on 2018-03-24 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='historyentry',
            options={'verbose_name': 'History Entry', 'verbose_name_plural': 'History Entries'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'User Information', 'verbose_name_plural': 'User Information'},
        ),
        migrations.AddField(
            model_name='product',
            name='size_primary',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_secondary',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historyentry',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historyentry',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='source',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='views',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='store',
            name='coupons',
        ),
        migrations.AddField(
            model_name='store',
            name='coupons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Coupon'),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='store',
            name='products',
        ),
        migrations.AddField(
            model_name='store',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Product'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='store',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.Cart'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.HistoryEntry'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='site_product_images', to='Site.Image'),
        ),
    ]
