# Generated by Django 2.0.2 on 2018-03-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_auto_20180324_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='history',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='site_userinfo_history', to='Site.HistoryEntry'),
        ),
    ]
