# Generated by Django 2.0.2 on 2018-03-23 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_auto_20180323_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='coupons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Coupon'),
        ),
        migrations.AddField(
            model_name='store',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Product'),
        ),
    ]
