# Generated by Django 2.0.2 on 2018-03-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_auto_20180323_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='site_cart_products', to='Site.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_primary',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_secondary',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
